### ISSUE TITLE
NUS-WIDE

### ISSUE THREAD

**Issue by KC777222** [Cherishnoobs/HEH#2]
想问一下为什么NUS数据集在验证的时候总是报错RuntimeError: CUDA error: device-side assert triggered

**Comment by Cherishnoobs** [comment]
具体报错的代码在哪个位置呢？

**Comment by KC777222** [comment]
> 具体报错的代码在哪个位置呢？

2024-03-18 17:11:57,549 - INFO - Epoch [2/70], Iter [312/312] Loss1: 0.5456 Loss2: 0.4146 Loss3: 0.6907 Loss4: 0.9500 Total Loss: 1.0705
2024-03-18 17:11:57,682 - INFO - --------------------Evaluation: Calculate top MAP-------------------
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [187,0,0], thread: [32,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.   
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
就是在验证的时候 def compress_nus(train_loader, test_loader, model_I, model_T, train_dataset, test_dataset, G_test):  但不知道是哪里出了问题

**Comment by KC777222** [comment]
> 具体报错的代码在哪个位置呢？
2024-03-18 17:11:57,549 - INFO - Epoch [2/70], Iter [312/312] Loss1: 0.5456 Loss2: 0.4146 Loss3: 0.6907 Loss4: 0.9500 Total Loss: 1.0705
2024-03-18 17:11:57,682 - INFO - --------------------Evaluation: Calculate top MAP-------------------
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:111: operator(): block: [187,0,0], thread: [32,0,0] Assertion failed.
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
就是在验证的时候 def compress_nus(train_loader, test_loader, model_I, model_T, train_dataset, test_dataset, G_test): 但不知道是哪里出了问题

**Comment by Cherishnoobs** [comment]
看着像是环境冲突，先试试在cpu上进行测试，如果cpu上能正常进行测试。可能是环境问题。

**Comment by KC777222** [comment]
> 看着像是环境冲突，先试试在cpu上进行测试，如果cpu上能正常进行测试。可能是环境问题。

应该不是环境问题吧，因为在flickr上可以正常跑

**Comment by Cherishnoobs** [comment]
We have temporarily uploaded the complete dirty code, please check
