### ISSUE TITLE
 The "freeze_support()" line can be omitted if the program         is not going to be frozen to produce an executable.

### ISSUE THREAD

**Issue by RRooyyCChheenn** [Cherishnoobs/HEH#4]

**Comment by Cherishnoobs** [comment]
That could be leftover dirty code

**Comment by RRooyyCChheenn** [comment]
then how can we solve that, do we have the clear code can be ran?

**Comment by Cherishnoobs** [comment]
The dirty version of the code will work just fine, but with more redundant and invalid code

**Comment by Cherishnoobs** [comment]
> The dirty version of the code will work just fine, but with more redundant and invalid code



> then how can we solve that, do we have the clear code can be ran?

The dirty version of the code will work just fine, but with more redundant and invalid code

**Comment by Cherishnoobs** [comment]
> then how can we solve that, do we have the clear code can be ran?


The dirty version of the code will work just fine, but with more redundant and invalid code

**Comment by RRooyyCChheenn** [comment]
but it just stuck on the "freeze_support()", and the code do not write anything in the log.txt
